name: test
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: setup
        run: make setup
      - name: test
        run: make test
      - name: lint
        run: make lint

